# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['team']},
        ),
    ]
