# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='utility',
            new_name='description',
        ),
    ]
