# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0002_auto_20160228_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
