# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0004_auto_20160229_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=140, null=True),
        ),
    ]
