# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0004_auto_20160225_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category',
        ),
    ]
