# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0005_auto_20160229_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
    ]
