# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0006_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scat.Category'),
        ),
    ]
