# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0007_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'static/images/logos'),
        ),
    ]
