# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0008_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'scat/static/images/people'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to=b'scat/static/images/categories'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'scat/static/images/logos'),
        ),
    ]
