# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import scat.models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0009_auto_20160302_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=scat.models.only_filename),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=scat.models.only_filename),
        ),
    ]
