# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0013_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='business_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scat.Person'),
        ),
    ]
