# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0015_auto_20160226_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='documentation',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
