# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0017_auto_20160226_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
