# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import scat.models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0018_auto_20160302_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, default=None, max_length=140, null=True)),
                ('image', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=scat.models.only_filename),
        ),
        migrations.AlterField(
            model_name='service',
            name='documentation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scat.Portfolio'),
        ),
    ]
