# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0018_auto_20160226_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
