# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0019_auto_20160226_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title']},
        ),
    ]
