# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import scat.models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0020_portfolioimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioimage',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='category',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=scat.models.only_filename),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=scat.models.only_filename),
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
