# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0021_auto_20160303_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scat.Portfolio'),
        ),
    ]
