# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0022_category_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scat.Portfolio'),
        ),
    ]
