# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0023_service_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_operations_manager',
        ),
        migrations.AddField(
            model_name='service',
            name='service_operations_manager',
            field=models.ManyToManyField(to='scat.Person'),
        ),
    ]
