# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0023_service_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Statu',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='status',
            new_name='statu',
        ),
    ]
