# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0024_auto_20160226_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statu',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='statu',
            new_name='status',
        ),
    ]
