# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0024_auto_20160304_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_operations_manager',
            new_name='som',
        ),
    ]
