# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0025_auto_20160226_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uun',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
