# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0025_auto_20160304_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
    ]
