# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0026_auto_20160226_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
