# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0026_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryimage',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
