# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0027_auto_20160226_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['college', 'school'],
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
    ]
