# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0028_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scat.Availability'),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scat.Location'),
        ),
    ]
