# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0029_auto_20160304_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'categories'},
        ),
    ]
