# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0031_service_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='team',
            field=models.CharField(max_length=200),
        ),
    ]
