# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0031_auto_20160304_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['name'], 'verbose_name_plural': 'people'},
        ),
    ]
