# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0032_auto_20160304_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['team'], 'verbose_name_plural': 'support'},
        ),
    ]
