# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0034_auto_20160304_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'status'},
        ),
    ]
