# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0036_auto_20160304_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='som',
            field=models.ManyToManyField(blank=True, null=True, to='scat.People'),
        ),
    ]
