# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0037_auto_20160304_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='som',
            field=models.ManyToManyField(to='scat.People'),
        ),
    ]
