# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0038_auto_20160305_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='visible',
            field=models.NullBooleanField(),
        ),
    ]
