# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0040_auto_20160305_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='published',
            field=models.BooleanField(default=0),
        ),
    ]
