# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0042_remove_service_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='som',
            field=models.ManyToManyField(null=True, to='scat.People'),
        ),
    ]
