# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0043_auto_20160305_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='som',
            field=models.ManyToManyField(default=None, to='scat.People'),
        ),
    ]
