# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0046_auto_20160306_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='availability',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scat.Availability'),
        ),
    ]
