# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0048_auto_20160307_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='availability',
            name='hours',
            field=models.CharField(max_length=200),
        ),
    ]
