# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0049_auto_20160307_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='guid',
            field=models.UUIDField(default=None),
        ),
    ]
