# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0052_auto_20160307_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='required',
            field=models.ManyToManyField(blank=True, related_name='_service_required_+', to='scat.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='requires',
            field=models.ManyToManyField(blank=True, related_name='_service_requires_+', to='scat.Service'),
        ),
    ]
