# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0053_auto_20160307_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
    ]
