# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0054_auto_20160307_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='som',
            new_name='service_operation_manager',
        ),
    ]
