# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0056_auto_20160307_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='required',
        ),
        migrations.AddField(
            model_name='service',
            name='required_by',
            field=models.ManyToManyField(blank=True, related_name='_service_required_by_+', to='scat.Service'),
        ),
    ]
