# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0057_auto_20160308_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='second_line_support',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_line_support', to='scat.Support'),
        ),
    ]
